### ISSUE TITLE
Support for OpenGL ES

### ISSUE THREAD

**Issue by cmarty** [kritzikratzi/ofxMightyUI#2]
Hello. Thanks for great GUI library. I like your approach.
I tried to use it on Raspberry Pi but I was stuck by ofxFontStash2 which is not using OpenGLES.
Do you think is there any hope ?

**Comment by kritzikratzi** [comment]
look at this: https://github.com/armadillu/ofxFontStash2/commits/feature/NanoVG_renderer
but it's all very fresh.

**Comment by emurray2** [comment]
Does this library work on the iPhone? I have tried compiling it and I am having some issues. Maybe it is because I'm new to using openFrameworks.

**Comment by emurray2** [comment]
Edit: My above response is not the case. @kritzikratzi  mentioned to me that ofxFontStash2 is on a custom branch without OpenGL ES support, which ofxMightyUI depends on. I then just read on the Apple Developer website https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Introduction/Introduction.html that OpenGL ES was deprecated on iOS 12. Potentially, we could start moving towards using Metal instead?

**Comment by kritzikratzi** [comment]
i think GLES is fine for another few years. there are quite a few cross-platform libraries out there that could be suited (bgfx, vulkan+moltenvk, skia,...), but imho just supporting gles should be good enough for now because it's not a major change. 

for major, breaking changes (i have a few things i'd do differently, mainly use smart pointers for everything) it's better to just use ofxMightyUI as a starting point for a new library.

**Comment by emurray2** [comment]
Oh ok that makes sense. So you can still use GL ES on iOS 13.1, it’s just encouraged that you try to switch later. Also I didn’t know smart pointers exist. You are a legend at programming! Thank you so much for the help!

**Comment by kritzikratzi** [comment]
well... it took a while, but gles support just landed on the of12_test branch :D
