### ISSUE TITLE
ofxFontSlash2 seem to be updated, making the addon deprecated 

### ISSUE THREAD

**Issue by EmersonSnow** [kritzikratzi/ofxMightyUI#4]
Hey,

I've added ofxFontSlash2 to project, however, it appears it been updated since it was wrote into your addon, causing a lot errors. I've tried hack and slash fix it, but with no success. I would be grateful if you could supply the version of ofxFontSlash2 you used, or update application. As it looks great!

All the Best

**Comment by moebiussurfing** [comment]
https://github.com/kritzikratzi/ofxFontStash2
that's his fork, didn't tested yet

**Comment by moebiussurfing** [comment]
linked command failed with exit code 1 here

**Comment by kritzikratzi** [comment]
hey! 

i'm still on OF 0.9.3., it might work in 9.8, it might not. 
for fontastash2, yes, it sortof depends on the branch https://github.com/kritzikratzi/ofxFontStash2

i just tried to create a new project with the 0.9.3. project generator, and it sets everything up correctly , except it's not copying ofxMightyUI/bin/data/* over to the project after building, so you have to do that manually once. 

btw: cleanup of this repo is very welcome. i'm using this for long term projects, so the ease of setup and compatibility to multiple OF versions is not a concern for me (i understand that it is something that everybody else cares about :) )

**Comment by EmersonSnow** [comment]
Okay, for the update and link to the fork! I'll give it ago in 0.93. I've decided I'm going to work on my own UI for personal use, I'm going use this as an example (if you don't mind), as well as some others. It sad ofxUI is deprecated now as that was best I used in older versions oF. I'm currently working on a piano keyboard addon, I needed UI for. Which is part of a bigger project which I might release, but I'm working in 0.98 so I can't use it!

**Comment by moebiussurfing** [comment]
ok @kritzikratzi
it working doing this tips.
should be nice if you share some other example btw.
thanks for the addon. i go check for it

**Comment by EmersonSnow** [comment]
@moebiussurfing When I get a chance to dig around, I'll create a fork (or whatever I'm new to GitHub) with some examples, I won't change the source code, I'll just create some examples. If @kritzikratzi is alright with that of course!

**Comment by EmersonSnow** [comment]
@kritzikratzi Would mind if I make fork and update it to 0.10? Much easier than making my own UI

**Comment by kritzikratzi** [comment]
no, the opposite -- i would love to update to the latest OF. 
the biggest challenge will be you'll have to merge the ofxFontStash2 from me and the original from armadillu (his version should either support OF-master directly, or there is a branch that does). 

if you wanna go through with this, ask anything anytime :)

**Comment by kritzikratzi** [comment]
this is a bit off topic here, but because there was some talk about contributions. 
here is what i think would make great pull changes:  

* add examples 
* add doxygen docs to the classes
* make it work in the new OF and upgrade to armadillus ofxFontStash2
* convert from raw pointers with new/delete to refcounting with shared_ptr/weak_ptr (weak_ptr for events and back refs to the parents, shared_ptrs for the the children) -- this is a giant change and imho would (together with all the other changes) justify forking it into a ofxMightyUI2
* multi window support
* instead using the OF event system (mousedown/touchdown, etc.) use something more universal like bakercp ofxPointer (this is also a big change and would only make sense in a ofxMightyUI2 fork). 

especially the first two, examples and doxygen, would be of the biggest value for others and i'll pull pretty much anything that improves the current situation.

**Comment by EmersonSnow** [comment]
Hey, sorry it taken so long to respond, I was doing some stuff outside openFrameworks. I've created a fork of the addon, and I'll be willing to put together some examples for project I'm working on. Whether I have ability to upgrade it to 0.10.0 - I don't know, but I can give it a try, as that's version my project is currently on. If I'm able to - I'll upgrade your fork of ofxFontStash2 to 0.10.0 rather than merging the original.

**Comment by kritzikratzi** [comment]
of10 finally works (see the of10 branch)
